version: "3.9"
services:
    nginx:
        image: "nginx:1.23.3-alpine"
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        links:
            - mariadb
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
        environment:
            XDEBUG_MODE: "debug"

    mariadb:
        image: "mariadb:10.10.2"
        working_dir: /app
        volumes:
            - ".:/app"
            - "./mariadb/data:/var/lib/mysql"
            - "./mariadb/logs:/var/log/mysql"
            - "./mariadb/conf:/etc/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "3308:3306"

    redis:
        image: "redis:7.0.7-alpine"
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
